Resources:
  KronoosUploadControlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: KronoosUploadControlTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
        - AttributeName: bytesRange
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
        - AttributeName: bytesRange
          KeyType: RANGE
